baseURL: "https://zibozhaosc.github.io" 
title: Zibo Zhao
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: research/
          weight: 5


params:
    description: "I am a research assistant at HKU business school, my research interest is labor economics and artificial intelligence."
    author: Zibo Zhao
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "July 2024"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["research"]
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Zibo Zhao
          subtitle: "I am an aspiring social science researcher specialized in the intersection between applied micro-economics and artificial intelligence. Currently I am a research assistant at HKU business school working with prof.Jie Gong. \n\n\n  I have worked on topics like building measurement for labor market with modern artificial intelligence models, the impact of human-ai collaboration on the creative production process, and building ai-tools for tabularizing semi-structured textual data.\n\n\n You can contact me at: andrewzhao054@gmail.com or zbzhao@hku.hk"
          imageUrl: "CCF2024-headpic.jpg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Zibo Zhao
          buttons:
            - name: Research
              url: research/

    socialIcons:
        - name: cv
          url: cv.pdf
        - name: Email
          url: mailto:andrewzhao054@gmail.com

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Zibo Zhao"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2